version: 2.1
orbs:
  notify: checkmoney/notify@1.1.0
jobs:
  roll_out:
    description: "Deploy container to server"

    parameters:
      ssh_user:
        type: env_var_name
      ssh_host:
        type: env_var_name
      image_name:
        type: string
      image_version:
        type: env_var_name
      path_to_app:
        type: env_var_name
      apply_post_install:
        type: boolean
        default: false
      container_name:
        type: string
      post_install_script:
        type: string

    machine:
      enabled: true

    steps:
      - run:
          name: Setup Env
          command: |
            VERSION="${<< parameters.image_version >>:-vlatest}"
            echo "export IMAGE_TAG=${VERSION:1}" >> $BASH_ENV
            echo "export PATH_TO_APP=${<< parameters.path_to_app >>}" >> $BASH_ENV
      - run:
          name: Deploy Over SSH
          command: |
            source $BASH_ENV
            ssh $<< parameters.ssh_user >>@$<< parameters.ssh_host >> "cd $PATH_TO_APP &&
              sudo docker pull checkmoney/<< parameters.image_name >>:$IMAGE_TAG &&
              sudo docker-compose down &&
              sed -i \"s/<< parameters.image_name >>:.*/<< parameters.image_name >>:$IMAGE_TAG/g\" ./docker-compose.yml &&
              sudo docker-compose up -d &&
              sudo docker image prune -f"
      - when:
          condition: << parameters.apply_post_install >>
          steps:
            - run:
                name: Deploy Over SSH
                command: |
                  source $BASH_ENV
                  ssh $<< parameters.ssh_user >>@$<< parameters.ssh_host >> "cd $PATH_TO_APP &&
                    docker-compose run << parameters.container_name >> << parameters.post_install_script >>"
      - notify/send:
          user: "-322096840"
          project: << parameters.image_name >>
          info: "Successfully delivered"
      - notify/send:
          user: "-322096840"
          project: << parameters.image_name >>
          info: "Alert! Delivery failed!"
          when: on_fail
      