version: 2.1
jobs:
  invoke:
    description: "Just run linters by @solid-soda/scripts"
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-dependencies-{{ checksum "yarn.lock" }}
            - node-dependencies-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: node-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Run linters
          command: yarn soda lint
