version: 2.1
jobs:
  lint:
    description: "Run static analysis for Flutter"
    docker:
      - image: cirrusci/flutter:v1.10.7
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dart-dependencies-{{ checksum "pubspec.lock" }}
            - dart-dependencies-
      - run: flutter pub get
      - run: flutter packages pub run build_runner build
      - save_cache:
          paths:
            - .dart_tool
          key: dart-dependencies-{{ checksum "pubspec.lock" }}
      - run: flutter analyze lib
  test:
    description: "Run tests for Flutter"
    docker:
      - image: cirrusci/flutter:v1.10.7
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dart-dependencies-{{ checksum "pubspec.lock" }}
            - dart-dependencies-
      - run: flutter pub get
      - run: flutter packages pub run build_runner build
      - save_cache:
          paths:
            - .dart_tool
          key: dart-dependencies-{{ checksum "pubspec.lock" }}
      - run: flutter test
